name: 'dbt_project'

model-paths: ["models"]

# files using the `{{ config(...) }}` macro.
models:
  dbt_project:
    +persist_docs:
      relation: true
      column: true
    stocks_source:
      schema: stocks
      meterialized: view
    stocks_date_count:
      schema: stocks
      meterialized: view
    movies_source:
      schema: movies
      materialized: view
    credits_source:
      schema: movies
      materialized: view
    cast_language:
      schema: movies
      materialized: view