
default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      pass: postgres
      dbname: postgres
      schema: postgres
      threads: 4
      keepalives_idle: 0